INSERT OR IGNORE INTO station (station_code, display_name, active) VALUES
('cap', 'Capital', 1),
('dj', 'Deejay', 1),
('fre', 'Freccia', 1),
('m2o', 'M2O', 1),
('101', 'R101', 1),
('rtl', 'RTL', 1),
('105', 'R105', 1),
('rds', 'RDS', 1),
('vir', 'Virgin', 1);


INSERT OR IGNORE INTO country (country_code, name) VALUES
('XX', 'World'),
('ZZ', 'World'),
('CN', 'China'),
('IN', 'India'),
('US', 'United States'),
('ID', 'Indonesia'),
('PK', 'Pakistan'),
('BR', 'Brazil'),
('NG', 'Nigeria'),
('BD', 'Bangladesh'),
('RU', 'Russia'),
('MX', 'Mexico'),
('JP', 'Japan'),
('ET', 'Ethiopia'),
('PH', 'Philippines'),
('EG', 'Egypt'),
('VN', 'Vietnam'),
('CD', 'Congo'),
('TR', 'Turkey'),
('IR', 'Iran'),
('DE', 'Germany'),
('TH', 'Thailand'),
('GB', 'United Kingdom'),
('FR', 'France'),
('IT', 'Italy'),
('TZ', 'Tanzania'),
('ZA', 'South Africa'),
('MM', 'Myanmar'),
('KE', 'Kenya'),
('KR', 'South Korea'),
('CO', 'Colombia'),
('ES', 'Spain'),
('UG', 'Uganda'),
('AR', 'Argentina'),
('DZ', 'Algeria'),
('SD', 'Sudan'),
('UA', 'Ukraine'),
('IQ', 'Iraq'),
('AF', 'Afghanistan'),
('PL', 'Poland'),
('CA', 'Canada'),
('MA', 'Morocco'),
('SA', 'Saudi Arabia'),
('UZ', 'Uzbekistan'),
('PE', 'Peru'),
('MY', 'Malaysia'),
('AO', 'Angola'),
('GH', 'Ghana'),
('MZ', 'Mozambique'),
('NP', 'Nepal'),
('YE', 'Yemen'),
('CH', 'Switzerland'),
('IE', 'Ireland');

INSERT OR IGNORE INTO song (song_title, song_performers) VALUES
('TODO', 'TODO');
